import { contentType } from '@optimizely/cms-sdk'

export const OT_ChartBlock = contentType({
  key: 'OT_ChartBlock',
  displayName: 'Chart Block',
  baseType: '_component',
  compositionBehaviors: ['elementEnabled', 'sectionEnabled'],
  properties: {
    heading: {
      type:        'string',
      displayName: 'Chart Title',
      description: 'Required. Displayed above the visualization.',
      group:       'OT_Content',
      sortOrder:   10,
      isLocalized: true,
      maxLength:   80,
    },
    subtext: {
      type:        'string',
      displayName: 'Supporting Label',
      description: 'Optional. Time period, data source attribution, or context note. e.g. "Source: FRED, 12-month trailing".',
      group:       'OT_Content',
      sortOrder:   20,
      isLocalized: true,
      maxLength:   120,
    },
    chartType: {
      type:        'string',
      displayName: 'Chart Type',
      description: 'Controls which Recharts visualization is rendered.',
      format:      'selectOne',
      enum: [
        { value: 'line',       displayName: 'Line — Trend Over Time' },
        { value: 'area',       displayName: 'Area — Volume or Growth' },
        { value: 'bar',        displayName: 'Bar — Comparison' },
        { value: 'barStacked', displayName: 'Bar Stacked — Composition' },
        { value: 'radial',     displayName: 'Radial — Single Score or KPI' },
      ],
      group:     'OT_Content',
      sortOrder: 30,
    },
    chartData: {
      type:        'string',
      displayName: 'Chart Data (JSON)',
      description: `Paste a JSON dataset. LINE/AREA/BAR STACKED: { "series": [{ "name": "…", "data": [1,2,3] }], "labels": ["Jan","Feb","Mar"] }. RADIAL: { "series": [{ "name": "…", "data": [84] }], "labels": ["Score"], "max": 100 }`,
      group:       'OT_Content',
      sortOrder:   40,
    },
    seriesColors: {
      type:        'string',
      displayName: 'Color Palette',
      description: 'Controls which color ramp is applied to chart series. Use Mono on brand-colored backgrounds.',
      format:      'selectOne',
      enum: [
        { value: 'brand',     displayName: 'Brand — Teal + Accent' },
        { value: 'warm',      displayName: 'Warm — Amber + Gold' },
        { value: 'cool',      displayName: 'Cool — Blue + Indigo' },
        { value: 'diverging', displayName: 'Diverging — Brand → Accent Arc' },
        { value: 'mono',      displayName: 'Mono — White alphas (brand/glass only)' },
      ],
      group:     'OT_Content',
      sortOrder: 50,
    },
    valuePrefix: {
      type:        'string',
      displayName: 'Value Prefix',
      description: 'Optional. Prepended to axis labels and tooltip values. e.g. $ £ €',
      group:       'OT_Content',
      sortOrder:   60,
      maxLength:   5,
    },
    valueSuffix: {
      type:        'string',
      displayName: 'Value Suffix',
      description: 'Optional. Appended to axis labels and tooltip values. e.g. % K bps pts',
      group:       'OT_Content',
      sortOrder:   70,
      maxLength:   5,
    },
    showLegend: {
      type:        'boolean',
      displayName: 'Show Legend',
      description: 'Toggle legend visibility. Recommended on for multi-series charts.',
      group:       'OT_Content',
      sortOrder:   80,
    },
    showGrid: {
      type:        'boolean',
      displayName: 'Show Grid Lines',
      description: 'Toggle chart grid lines.',
      group:       'OT_Content',
      sortOrder:   90,
    },
  },
})
